"""initial HR and payroll schema

Revision ID: b9cf01dcfd2b
Revises: 
Create Date: 2026-09-05 15:53:38.096145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9cf01dcfd2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_paid', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_leave_types_code')
    )
    op.create_table('salary_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_categories_code'), 'salary_categories', ['code'], unique=True)
    op.create_table('salary_structures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('working_days', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('daily_working_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_schedules_name')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'ON_LEAVE', 'HOLIDAY', name='attendance_status'), server_default='PRESENT', nullable=False),
    sa.Column('worked_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'attendance_date', name='uq_attendance_employee_date')
    )
    op.create_index(op.f('ix_attendance_records_attendance_date'), 'attendance_records', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('job_position', sa.String(), nullable=True),
    sa.Column('salary_structure_id', sa.UUID(), nullable=False),
    sa.Column('wage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='contract_status'), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_employee_id'), 'contracts', ['employee_id'], unique=False)
    op.create_table('payruns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('salary_structure_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('employee_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'COMPUTED', 'VALIDATED', 'PAID', name='payrun_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payruns_salary_structure_id'), 'payruns', ['salary_structure_id'], unique=False)
    op.create_table('salary_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('computation_type', sa.Enum('FIXED', 'PERCENTAGE', 'FORMULA', name='computation_type'), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['salary_categories.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['salary_structures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'code', name='uq_salary_rule_structure_code')
    )
    op.create_index(op.f('ix_salary_rules_category_id'), 'salary_rules', ['category_id'], unique=False)
    op.create_index(op.f('ix_salary_rules_structure_id'), 'salary_rules', ['structure_id'], unique=False)
    op.create_table('time_off_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('number_of_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leave_request_status'), server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_off_requests_employee_id'), 'time_off_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_time_off_requests_leave_type_id'), 'time_off_requests', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_time_off_requests_status'), 'time_off_requests', ['status'], unique=False)
    op.create_table('payslips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payrun_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('salary_structure_id', sa.UUID(), nullable=False),
    sa.Column('worked_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COMPUTED', 'VALIDATED', 'PAID', name='payrun_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payrun_id'], ['payruns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payrun_id', 'employee_id', name='uq_payslip_payrun_employee')
    )
    op.create_index(op.f('ix_payslips_contract_id'), 'payslips', ['contract_id'], unique=False)
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslips_payrun_id'), 'payslips', ['payrun_id'], unique=False)
    op.create_index(op.f('ix_payslips_salary_structure_id'), 'payslips', ['salary_structure_id'], unique=False)
    op.create_table('payslip_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payslip_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['salary_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslip_lines_payslip_id'), 'payslip_lines', ['payslip_id'], unique=False)
    op.create_index(op.f('ix_payslip_lines_rule_id'), 'payslip_lines', ['rule_id'], unique=False)
    employee_type_enum = postgresql.ENUM(
        'FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN',
        name='employee_type',
    )
    employee_status_enum = postgresql.ENUM(
        'ACTIVE', 'INACTIVE', 'ON_LEAVE', 'TERMINATED',
        name='employee_status',
    )
    employee_type_enum.create(op.get_bind(), checkfirst=True)
    employee_status_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        'employees', 'phone',
        existing_type=sa.VARCHAR(length=20),
        type_=sa.VARCHAR(length=30),
    )
    op.alter_column(
        'employees', 'job_position',
        existing_type=sa.VARCHAR(length=150),
        type_=sa.VARCHAR(length=120),
    )
    op.alter_column(
        'employees', 'employee_type',
        existing_type=sa.VARCHAR(length=50),
        type_=employee_type_enum,
        postgresql_using='employee_type::employee_type',
        existing_nullable=False,
    )
    op.alter_column(
        'employees', 'status',
        existing_type=sa.VARCHAR(length=30),
        type_=employee_status_enum,
        postgresql_using='status::employee_status',
        existing_nullable=False,
    )

    op.execute("SET TIME ZONE 'UTC'")

    op.alter_column(
        'employees', 'created_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        postgresql_using="created_at AT TIME ZONE 'UTC'",
        existing_nullable=False,
    )
    op.alter_column(
        'employees', 'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        postgresql_using="updated_at AT TIME ZONE 'UTC'",
        existing_nullable=False,
    )

    op.drop_constraint('employees_email_key', 'employees', type_='unique')
    op.create_index('ix_employees_email', 'employees', ['email'], unique=True)

    op.drop_constraint('employees_employee_code_key', 'employees', type_='unique')
    op.create_index('ix_employees_employee_code', 'employees', ['employee_code'], unique=True)

    op.create_foreign_key(
        'fk_employees_manager_id_employees',
        'employees',
        'employees',
        ['manager_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_employees_manager_id_employees',
        'employees',
        type_='foreignkey',
    )

    op.drop_index('ix_employees_employee_code', table_name='employees')
    op.create_unique_constraint(
        'employees_employee_code_key',
        'employees',
        ['employee_code'],
        postgresql_nulls_not_distinct=False,
    )

    op.drop_index('ix_employees_email', table_name='employees')
    op.create_unique_constraint(
        'employees_email_key',
        'employees',
        ['email'],
        postgresql_nulls_not_distinct=False,
    )

    op.alter_column(
        'employees', 'updated_at',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        postgresql_using="updated_at AT TIME ZONE 'UTC'",
        existing_nullable=False,
    )
    op.alter_column(
        'employees', 'created_at',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        postgresql_using="created_at AT TIME ZONE 'UTC'",
        existing_nullable=False,
    )

    op.alter_column(
        'employees', 'status',
        existing_type=postgresql.ENUM(
            'ACTIVE', 'INACTIVE', 'ON_LEAVE', 'TERMINATED',
            name='employee_status',
        ),
        type_=sa.VARCHAR(length=30),
        postgresql_using='status::text',
        existing_nullable=False,
    )
    op.alter_column(
        'employees', 'employee_type',
        existing_type=postgresql.ENUM(
            'FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN',
            name='employee_type',
        ),
        type_=sa.VARCHAR(length=50),
        postgresql_using='employee_type::text',
        existing_nullable=False,
    )

    op.alter_column(
        'employees', 'job_position',
        existing_type=sa.VARCHAR(length=120),
        type_=sa.VARCHAR(length=150),
        existing_nullable=True,
    )
    op.alter_column(
        'employees', 'phone',
        existing_type=sa.VARCHAR(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )

    postgresql.ENUM(
        name='employee_status'
    ).drop(op.get_bind(), checkfirst=True)

    postgresql.ENUM(
        name='employee_type'
    ).drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_payslip_lines_rule_id'), table_name='payslip_lines')
    op.drop_index(op.f('ix_payslip_lines_payslip_id'), table_name='payslip_lines')
    op.drop_table('payslip_lines')
    op.drop_index(op.f('ix_payslips_salary_structure_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_payrun_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_contract_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_time_off_requests_status'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_leave_type_id'), table_name='time_off_requests')
    op.drop_index(op.f('ix_time_off_requests_employee_id'), table_name='time_off_requests')
    op.drop_table('time_off_requests')
    op.drop_index(op.f('ix_salary_rules_structure_id'), table_name='salary_rules')
    op.drop_index(op.f('ix_salary_rules_category_id'), table_name='salary_rules')
    op.drop_table('salary_rules')
    op.drop_index(op.f('ix_payruns_salary_structure_id'), table_name='payruns')
    op.drop_table('payruns')
    op.drop_index(op.f('ix_contracts_employee_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_attendance_date'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_table('schedules')
    op.drop_table('salary_structures')
    op.drop_index(op.f('ix_salary_categories_code'), table_name='salary_categories')
    op.drop_table('salary_categories')
    op.drop_table('leave_types')
    # ### end Alembic commands ###
